### ISSUE TITLE
Adam, I made a bunch of changes/updates in the TranTesting branch...see comments.

### ISSUE THREAD

**Issue by ctran88** [aking6083/kingTranAssn3#3]
Adam,

I think I fixed your initSeperateChain() function!  Here is a list of changes:

-isDupe() changed to be a sequential search w/sentinel algorithm.
-createList() changed to accomodate sentinel search.
-initSeperateChain() changed so you can initialize array of pointers to NULL without a constant value.  You can also access data within the array (at least with my bit of test code)
-main() changed to reflect testing
-kingFunctions.cpp: I commented out everything below initSeperateChain() to test the program.

For full changes, see all of my comments in the code itself.  I documented changes and reasoning.  I hope this works for you!

Chris

**Comment by aking6083** [comment]
Alright pulled my head out of my ass!!!  Ready to go now,
 I used the static int [] to increase search speed, I understand the sentinel search, but the list is not sorted so how do you not search the entire list for a duplicate value? 

I usually comment all my files at the end when I pour over my code, I should do like you and comment as I go, because I do cry about hour number 2 of commenting 1000+ lines,,

I appreciate your help!!  Sometimes my thinking gets cloudy and I end up breaking more than I fix, Thank God for source Control.  

Alright, not a night owl and havent slept 4 hours each night this week.  I am going to bed in about 15 minutes. 

Having Fun!

AK

**Comment by ctran88** [comment]
You do have to search the entire list for a duplicate value with the sentinel search, but only what's been added to the list so far.  Before, it was searching all 5000 indexes every time (from the first insert to the last).

Hahah yeah I used to comment at the end too but it was getting ridiculous...

I will keep at it and try to finish my array insertion function today and maybe get started on the display function.

CT
